### ISSUE TITLE
[WIP Plan] Version 1.0.0

### ISSUE THREAD

**Issue by Im5tu** [Im5tu/OpenMessage#26]
It's been a long while since this project got any love, so it's time to embark on a big upgrade of the components to modern thinking.

## Design

- Each provider will be constructed as a unique hosted service;
- Each provider publishes a new `Message` type to a central channel, simplifying the current design;
- Consumer of the new `Message` type will have standardised extension points and 
- `Message` type:
  * Abstract by design so that consumers can register capabilities, eg: `INegativelyAck`, `IDeferable` etc.

## Providers

Since the original use case for the library existing has moved on. It's worth taking a look at newer providers and getting them into the ecosystem.

- [x] Apache Kafka #21 (**NEW!**)
- [x] AWS SQS #23 (**NEW!**)
- [x] AWS SNS (**NEW!**)
- [ ] AWS Kinesis (**NEW!**)
- [ ] AWS EventBridge (**NEW!**)
- [ ] Azure Event Hubs #27 
- [ ] Azure Service Bus #28
- [x] InMemory 
- [ ] NATS #25  (**NEW!**)
- [ ] RabbitMq #22 (**NEW!**)

## Serializers

The serializers are massively out of date and could do with an upgrade. Provide integrations for the following:

- [x] Hyperion  (**NEW!**)
- [x] Jil
- [x] JsonDotNet
- [x] MessagePack (**NEW!**)
- [x] MsgPack (**NEW!**)
- [x] Protobuf (**NEW!**)
- [x] ServiceStackJson (**NEW!**)
- [x] Utf8Json (**NEW!**)
- [x] Wire (**NEW!**)

**Comment by Im5tu** [comment]
Update:

The base of the new structure is in place with the Kafka provider written from the ground up. All the serializers have been written but all need thorough testing. The Kafka provider peaked around 43k messages/sec locally which is quite nice. Handlers aren't doing much though.

Aiming to get basic support for all the providers first before going through a mass testing phase
